[project]
name = "sim_human"
version = "0.8.28"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cvxpy>=1.7.2",
    "imageio>=2.37.0",
    "matplotlib>=3.10.6",
    "mujoco>=3.3.5",
    "numpy>=2.2.6",
]
