services:
  wearable_mujoco_simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wearable_mujoco_simulation
    volumes:
      - ../:/wearable_ws/src/sim_human:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
      - ROS_PYTHON_VERSION=3
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash
    #command: bash -c "source /opt/ros/humble/setup.bash && source .venv/bin/activate && python sim_human/simulation.py"
    #command: bash -c "source /opt/ros/humble/setup.bash && source .venv/bin/activate && python sim_human/simulation.py"
