services:
  wearable_robot_simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wearable_robot_mujoco
    volumes:
      - ../:/wearable_ws/src/wearable_robot_mujoco:rw
      - ../../Patient:/wearable_ws/Patient:rw
      - ../../Index.dat:/wearable_ws/Index.dat:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
      - ROS_PYTHON_VERSION=3
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash
    #command: bash -c "source /opt/ros/humble/setup.bash && source .venv/bin/activate && python wearable_robot_mujoco/simulation.py"
